// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI3IZp1hOmWJwI7fZw0-KJb-5mWMW1itA',
    appId: '1:1075848695706:web:81aea159a504bbfe0d3423',
    messagingSenderId: '1075848695706',
    projectId: 'vnhope-8dee0',
    authDomain: 'vnhope-8dee0.firebaseapp.com',
    storageBucket: 'vnhope-8dee0.firebasestorage.app',
    measurementId: 'G-2MWW8X82YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEFPhj735oWibs4He15_3Z8gLFTPWl5EI',
    appId: '1:1075848695706:android:7409c13d4c62f6830d3423',
    messagingSenderId: '1075848695706',
    projectId: 'vnhope-8dee0',
    storageBucket: 'vnhope-8dee0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxdhm0LXnjXhPhx6KP7ONjcbhquYrmuHE',
    appId: '1:1075848695706:ios:ad20c815876a99b20d3423',
    messagingSenderId: '1075848695706',
    projectId: 'vnhope-8dee0',
    storageBucket: 'vnhope-8dee0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxdhm0LXnjXhPhx6KP7ONjcbhquYrmuHE',
    appId: '1:1075848695706:ios:ad20c815876a99b20d3423',
    messagingSenderId: '1075848695706',
    projectId: 'vnhope-8dee0',
    storageBucket: 'vnhope-8dee0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI3IZp1hOmWJwI7fZw0-KJb-5mWMW1itA',
    appId: '1:1075848695706:web:d9290f80ee2cec1b0d3423',
    messagingSenderId: '1075848695706',
    projectId: 'vnhope-8dee0',
    authDomain: 'vnhope-8dee0.firebaseapp.com',
    storageBucket: 'vnhope-8dee0.firebasestorage.app',
    measurementId: 'G-7J87GTCF9K',
  );
}
